#!/usr/bin/env python3.12
"""Convert Claude agent .md files to Codex .toml format.

Reads agents/*.md from the repo and writes distributable Codex agents to
agents-codex/.

Mapping:
  name        -> name (TOML basic string)
  description -> description (TOML basic string)
  model       -> model + model_reasoning_effort (per repo policy)
  read tools  -> sandbox_mode = "read-only"
  body        -> developer_instructions (TOML literal multi-line string)

Requires Python 3.11+ (uses tomllib for post-check validation). The shebang
pins 3.12; invoke explicitly with `python3.12 convert.py` if running on a
machine where the shebang lookup misses.

Run from the repo root:
  commands/sync-codex-agents/scripts/convert.py

Exit code is 0 on success, 1 on any post-check failure (TOML parse, missing
fields, body mismatch, or Claude-only tool reference).
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
AGENTS_DIR = REPO_ROOT / "agents"
OUTPUT_DIR = REPO_ROOT / "agents-codex"
GENERATED_HEADER = "# Generated by commands/sync-codex-agents/scripts/convert.py; do not edit."

MODEL_MAP = {
    "opus": ("gpt-5.6-terra", "high"),
    "sonnet": ("gpt-5.6-luna", "xhigh"),
}

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
KEY_VALUE_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)\s*:\s*(.*)$")


class ConvertError(Exception):
    pass


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        raise ConvertError("no YAML frontmatter found")
    raw_fm, body = m.group(1), m.group(2)
    fields: dict[str, str] = {}
    for line in raw_fm.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        km = KEY_VALUE_RE.match(line)
        if not km:
            continue
        key, value = km.group(1), km.group(2).strip()
        if value.startswith('"') and value.endswith('"') and len(value) >= 2:
            value = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
        fields[key] = value
    return fields, body.lstrip("\n")


def escape_toml_basic(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def translate_body(body: str) -> str:
    return (
        body.replace(
            "use `AskUserQuestion` to clarify",
            "use `request_user_input` to clarify when available; otherwise ask a concise plain-text question",
        )
        .replace(
            "use `AskUserQuestion` to ask",
            "use `request_user_input` when available; otherwise ask a concise plain-text question",
        )
        .replace("`AskUserQuestion`", "`request_user_input`")
    )


def render_toml(fields: dict[str, str], body: str) -> str:
    name = fields["name"]
    description = fields["description"]
    output_fields = [
        GENERATED_HEADER,
        f'name = "{escape_toml_basic(name)}"',
        f'description = "{escape_toml_basic(description)}"',
    ]
    claude_model = fields.get("model")
    if claude_model:
        if claude_model not in MODEL_MAP:
            raise ConvertError(f"{name}: unsupported Claude model {claude_model!r}")
        model, effort = MODEL_MAP[claude_model]
        output_fields.extend(
            [
                f'model = "{model}"',
                f'model_reasoning_effort = "{effort}"',
            ]
        )
    tools = {tool.strip() for tool in fields.get("tools", "").split(",")}
    if tools and not tools.intersection({"Edit", "Write"}):
        output_fields.append('sandbox_mode = "read-only"')
    # TOML trims a single newline immediately after the opening delimiter, so
    # `'''\n{body}'''` round-trips to `body` exactly. Adding a `\n` before the
    # closing `'''` would inject an extra newline into the parsed value.
    if "'''" in body:
        escaped_body = body.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
        instr_field = f'developer_instructions = """\n{escaped_body}"""'
    else:
        instr_field = f"developer_instructions = '''\n{body}'''"
    output_fields.append(instr_field)
    return "\n".join(output_fields) + "\n"


def convert_file(src: Path, dst_dir: Path) -> tuple[Path, dict[str, str]]:
    text = src.read_text(encoding="utf-8")
    fields, body = parse_frontmatter(text)
    name = fields.get("name")
    description = fields.get("description")
    if not name:
        raise ConvertError(f"{src.name}: missing 'name' in frontmatter")
    if not description:
        raise ConvertError(f"{src.name}: missing 'description' in frontmatter")
    if not body.strip():
        raise ConvertError(f"{src.name}: empty body")
    dst = dst_dir / f"{name}.toml"
    if dst.exists() and not dst.read_text(encoding="utf-8").startswith(
        GENERATED_HEADER
    ):
        raise ConvertError(f"{dst.name}: refusing to overwrite hand-authored file")
    translated_body = translate_body(body)
    dst.write_text(render_toml(fields, translated_body), encoding="utf-8")
    expected = {
        "name": name,
        "description": description,
        "body": translated_body,
    }
    if fields.get("model"):
        expected["model"], expected["model_reasoning_effort"] = MODEL_MAP[
            fields["model"]
        ]
    tools = {tool.strip() for tool in fields.get("tools", "").split(",")}
    if tools and not tools.intersection({"Edit", "Write"}):
        expected["sandbox_mode"] = "read-only"
    return dst, expected


def post_check(dst: Path, expected: dict[str, str]) -> list[str]:
    """Deterministic post-checks. Returns a list of error messages (empty = OK)."""
    errors: list[str] = []
    raw = dst.read_bytes()
    try:
        parsed = tomllib.loads(raw.decode("utf-8"))
    except tomllib.TOMLDecodeError as e:
        return [f"{dst.name}: TOML parse failed: {e}"]

    for key in ("name", "description", "developer_instructions"):
        if key not in parsed:
            errors.append(f"{dst.name}: missing key '{key}'")
    if errors:
        return errors

    if parsed["name"] != expected["name"]:
        errors.append(
            f"{dst.name}: name mismatch "
            f"(expected {expected['name']!r}, got {parsed['name']!r})"
        )
    if parsed["description"] != expected["description"]:
        errors.append(f"{dst.name}: description does not round-trip")
    for key in ("model", "model_reasoning_effort", "sandbox_mode"):
        if key in expected and parsed.get(key) != expected[key]:
            errors.append(f"{dst.name}: {key} does not match the source mapping")
    if dst.stem != expected["name"]:
        errors.append(
            f"{dst.name}: filename stem {dst.stem!r} != name {expected['name']!r}"
        )
    instr = parsed["developer_instructions"]
    if not instr.strip():
        errors.append(f"{dst.name}: developer_instructions empty after parse")
    if instr != expected["body"]:
        errors.append(
            f"{dst.name}: developer_instructions does not round-trip "
            f"({len(instr)} chars parsed vs {len(expected['body'])} expected)"
        )
    if "AskUserQuestion" in instr:
        errors.append(f"{dst.name}: Claude-only AskUserQuestion leaked into output")
    return errors


def main() -> int:
    if not AGENTS_DIR.is_dir():
        print(f"error: {AGENTS_DIR} does not exist", file=sys.stderr)
        return 1
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    # Remove only generated outputs so hand-authored project agents are safe.
    for old in OUTPUT_DIR.glob("*.toml"):
        if old.read_text(encoding="utf-8").startswith(GENERATED_HEADER):
            old.unlink()

    converted: list[Path] = []
    all_errors: list[str] = []

    for src in sorted(AGENTS_DIR.glob("*.md")):
        try:
            result = convert_file(src, OUTPUT_DIR)
        except ConvertError as e:
            all_errors.append(str(e))
            continue
        dst, expected = result
        errors = post_check(dst, expected)
        if errors:
            all_errors.extend(errors)
        converted.append(dst)

    print(f"Converted: {len(converted)}")
    for p in converted:
        print(f"  {p.relative_to(REPO_ROOT)}")
    if all_errors:
        print(f"\nFAILED post-checks: {len(all_errors)}", file=sys.stderr)
        for e in all_errors:
            print(f"  {e}", file=sys.stderr)
        return 1
    print("\nAll post-checks passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
